#!/usr/bin/env python3
"""
hybrid-search CLI — query the Hybrid Search API from your terminal and get a
proper, LLM-synthesized answer (not just raw chunks).

Usage:
  python cli.py "how does pgvector work"
  python cli.py "RAG pipelines" --max 8
  python cli.py "vector similarity" --graph
  python cli.py "docker networking" --json
  python cli.py --health

The answer is generated by the local Ollama model wired into the API. If Ollama
is not running, the CLI still prints the retrieved sources.
"""

import argparse
import json
import sys
import textwrap
import urllib.error
import urllib.request

DEFAULT_HOST = "http://localhost:8000"
DEFAULT_OLLAMA = "http://localhost:11434"

# localhost calls must never traverse a proxy — an HTTP_PROXY / ALL_PROXY
# environment variable would black-hole requests to localhost. This opener
# has proxies explicitly disabled.
_OPENER = urllib.request.build_opener(urllib.request.ProxyHandler({}))

_RESET = "\033[0m"
_BOLD = "\033[1m"
_DIM = "\033[2m"
_CYAN = "\033[36m"
_GREEN = "\033[32m"
_YELLOW = "\033[33m"
_RED = "\033[31m"
_BLUE = "\033[34m"
_MAGENTA = "\033[35m"


def _c(text, *codes):
    """Apply ANSI colour codes when stdout is a TTY."""
    if not sys.stdout.isatty():
        return str(text)
    return "".join(codes) + str(text) + _RESET


def _request(host, path, payload=None, method="GET"):
    data = json.dumps(payload).encode() if payload is not None else None
    headers = {"Content-Type": "application/json"} if data else {}
    req = urllib.request.Request(host + path, data=data, headers=headers, method=method)
    try:
        with _OPENER.open(req, timeout=180) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        try:
            body = json.loads(e.read())
            detail = body.get("detail", e.reason)
        except Exception:  # noqa: BLE001
            detail = e.reason
        print(_c(f"\n  Error {e.code}: {detail}", _RED), file=sys.stderr)
        sys.exit(1)
    except urllib.error.URLError as e:
        print(_c(f"\n  Cannot connect to {host}\n"
                 f"  Is the server running?  Try: uvicorn app.main:app --reload\n"
                 f"  Reason: {e.reason}", _RED), file=sys.stderr)
        sys.exit(1)


def _rule(char="─", width=74):
    return _c(char * width, _DIM)


def _wrap(text, width=74, indent=""):
    out = []
    for para in text.split("\n"):
        if not para.strip():
            out.append("")
            continue
        out.extend(textwrap.wrap(para, width=width,
                                 initial_indent=indent, subsequent_indent=indent)
                   or [indent])
    return "\n".join(out)


def _highlight_citations(text):
    """Make [1] [2] citation markers stand out."""
    if not sys.stdout.isatty():
        return text
    import re
    return re.sub(r"\[(\d+)\]",
                  lambda m: _BOLD + _CYAN + m.group(0) + _RESET, text)


def cmd_health(host):
    data = _request(host, "/api/v1/health")
    status = data.get("status", "unknown")
    colour = _GREEN if status == "healthy" else _YELLOW
    print(f"\n  {_c('API', _BOLD)}  {_c(status.upper(), colour, _BOLD)}"
          f"   v{data.get('version', '?')}")
    for name, comp in (data.get("components") or {}).items():
        st = comp.get("status", "?")
        c = _GREEN if st == "ok" else (_YELLOW if st == "slow" else _RED)
        lat = f"  {comp['latency_ms']}ms" if comp.get("latency_ms") is not None else ""
        print(f"    {name:<12} {_c(st.upper(), c)}{_c(lat, _DIM)}")
    print()


def cmd_search(host, query, max_results, graph, as_json, show_sources):
    if graph:
        data = _request(host, "/api/v1/search/graph",
                         {"query": query, "hops": 2, "seed_k": 5, "top_k": 20}, "POST")
    else:
        data = _request(host, "/api/v1/search",
                        {"query": query, "max_results": max_results}, "POST")

    if as_json:
        print(json.dumps(data, indent=2))
        return

    if graph:
        _render_graph(data)
        return

    # ---- header ----
    deg = _c("  ⚠ degraded", _YELLOW) if data.get("degraded") else ""
    print()
    print(_rule("━"))
    print(f"  {_c('QUERY', _DIM)}  {_c(query, _BOLD)}")
    print(f"  {_c(str(data.get('total_results', 0)) + ' sources', _DIM)}"
          f"  {_c('·', _DIM)}  {_c(str(data.get('processing_time_ms', 0)) + 'ms', _DIM)}"
          f"{'  ·  ' + _c('cached', _DIM) if data.get('cache_hit') else ''}{deg}")
    print(_rule("━"))

    # ---- the answer ----
    answer = data.get("answer", "")
    print(f"\n  {_c('🧠 ANSWER', _BOLD, _MAGENTA)}", end="")
    if data.get("answer_model"):
        print(f"  {_c('(' + data['answer_model'] + ')', _DIM)}")
    else:
        print()
    print()
    if answer:
        print(_highlight_citations(_wrap(answer, indent="  ")))
    else:
        print(_c("  No synthesized answer — the local LLM is not running.", _YELLOW))
        print(_c("  Start it:  ollama serve   &&   ollama pull llama3.2", _DIM))

    # ---- sources ----
    results = data.get("results", [])
    if show_sources and results:
        print(f"\n  {_c('SOURCES', _BOLD)}")
        print(_rule())
        for r in results:
            tag = _c(f"[{r['rank']}]", _BOLD, _CYAN)
            score = _c(f"score {r['score']:.3f}", _DIM)
            print(f"  {tag} {_c(r['title'], _BOLD)}  {score}")
            print(f"      {_c(r['url'], _BLUE)}")
            snippet = (r.get("content") or "").strip().replace("\n", " ")
            if snippet:
                print(_c(_wrap(snippet[:220] + "…", width=68, indent="      "), _DIM))
            print()

    # ---- trace ----
    trace = data.get("trace", [])
    if trace:
        cells = []
        for t in trace:
            st = t["status"]
            c = (_GREEN if st == "success" else _YELLOW if st in ("fallback", "skipped")
                 else _RED)
            cells.append(f"{t['stage']}:{_c(st, c)}")
        print(f"  {_c('pipeline', _DIM)}  " + _c(" → ", _DIM).join(cells))
        print()


def _render_graph(data):
    print()
    print(_rule("━"))
    print(f"  {_c('KNOWLEDGE GRAPH', _BOLD)}  "
          f"{_c(str(data.get('total_chunks', 0)) + ' chunks', _DIM)}")
    print(_rule("━"))
    seeds = data.get("seed_chunks", [])
    conn = data.get("connected_chunks", [])
    if not seeds and not conn:
        print(_c("\n  No graph results. Build the graph first:", _YELLOW))
        print(_c("  1) POST /api/v1/search/embed-and-store", _DIM))
        print(_c("  2) POST /api/v1/graph/build", _DIM))
        print()
        return
    for c in seeds:
        sim = c.get("similarity")
        sim_s = f"  sim {sim:.3f}" if isinstance(sim, (int, float)) else ""
        print(f"\n  {_c('SEED', _BOLD, _CYAN)}  "
              f"{_c(c.get('title', 'chunk'), _BOLD)}{_c(sim_s, _DIM)}")
        print(_c(_wrap((c.get("text") or "")[:220], indent="    "), _DIM))
    for c in conn:
        print(f"\n  {_c('HOP ' + str(c.get('hop', 1)), _BOLD, _YELLOW)}  "
              f"{_c(c.get('title', 'chunk'), _BOLD)}")
        print(_c(_wrap((c.get("text") or "")[:220], indent="    "), _DIM))
    print()


def cmd_test_llm(ollama, model):
    """Directly probe Ollama: reachable? model pulled? can it generate?"""
    import time
    print(f"\n  {_c('LLM DIAGNOSTIC', _BOLD)}   {_c(ollama + '  ·  model: ' + model, _DIM)}")
    print(_rule())

    # 1) reachable + 2) model present
    try:
        with _OPENER.open(ollama + "/api/tags", timeout=10) as r:
            tags = json.loads(r.read())
        models = [m.get("name", "") for m in tags.get("models", [])]
        print(f"  {_c('[1]', _GREEN)} Ollama reachable  {_c(f'({len(models)} model(s))', _DIM)}")
        if any(m.split(":")[0] == model.split(":")[0] for m in models):
            print(f"  {_c('[2]', _GREEN)} model '{model}' is available")
        else:
            print(f"  {_c('[2]', _RED)} model '{model}' NOT found")
            print(_c(f"      available: {', '.join(models) or 'none'}", _DIM))
            print(_c(f"      fix:  ollama pull {model}", _YELLOW))
            return
    except Exception as e:  # noqa: BLE001
        print(f"  {_c('[1]', _RED)} Ollama NOT reachable: {e}")
        print(_c("      fix:  start the Ollama app (Windows) or run `ollama serve`", _YELLOW))
        return

    # 3) generation works
    print(f"  {_c('[3]', _DIM)} generating a test answer…")
    t0 = time.time()
    try:
        body = json.dumps({"model": model, "prompt": "Reply with exactly: OK",
                           "stream": False, "options": {"num_predict": 10}}).encode()
        req = urllib.request.Request(ollama + "/api/generate", data=body,
                                     headers={"Content-Type": "application/json"},
                                     method="POST")
        with _OPENER.open(req, timeout=240) as r:
            out = json.loads(r.read())
        dt = time.time() - t0
        reply = (out.get("response") or "").strip()
        print(f"  {_c('[3]', _GREEN)} generation OK in {dt:.1f}s"
              f"  {_c('-> ' + reply[:40], _DIM)}")
        print(_c("\n  LLM step is working. Run a search to get synthesized answers.", _GREEN))
        if dt > 30:
            print(_c("  (first call is slow — the model loads into RAM; "
                     "later calls are fast)", _DIM))
    except Exception as e:  # noqa: BLE001
        print(f"  {_c('[3]', _RED)} generation failed: {e}")
    print()


def main():
    p = argparse.ArgumentParser(
        description="Query the Hybrid Search API and get an LLM-synthesized answer.")
    p.add_argument("query", nargs="?", help="the question to ask")
    p.add_argument("--host", default=DEFAULT_HOST, help="API host (default %(default)s)")
    p.add_argument("--max", type=int, default=5, dest="max_results",
                   help="max sources to retrieve (default 5)")
    p.add_argument("--graph", action="store_true", help="query the knowledge graph")
    p.add_argument("--json", action="store_true", dest="as_json", help="raw JSON output")
    p.add_argument("--no-sources", action="store_true", help="answer only, hide sources")
    p.add_argument("--health", action="store_true", help="check API health and exit")
    p.add_argument("--test-llm", action="store_true",
                   help="diagnose the local Ollama LLM and exit")
    p.add_argument("--ollama", default=DEFAULT_OLLAMA,
                   help="Ollama host for --test-llm (default %(default)s)")
    p.add_argument("--model", default="qwen2.5:1.5b",
                   help="Ollama model for --test-llm (default %(default)s)")
    args = p.parse_args()

    if args.test_llm:
        cmd_test_llm(args.ollama, args.model)
        return
    if args.health:
        cmd_health(args.host)
        return
    if not args.query:
        p.error("a query is required (or use --health / --test-llm)")
    cmd_search(args.host, args.query, args.max_results, args.graph,
               args.as_json, not args.no_sources)


if __name__ == "__main__":
    main()
